### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Timokaproka** [tealreal/hdheadfinal#1]
It gives an error and does not start.
Log link: https://gist.github.com/Timokaproka/2187c763a7529a4e77c676ad5b8a6496

**Comment by tealreal** [comment]
Hi, thanks for using my mod.

Newest release should fix it, just had to swap two lines of code.

**Comment by Timokaproka** [comment]
Thank you so much for still supporting this wonderful mod. The new update fixed everything
